package Ascenso.sytem.product.util;

import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

@Repository
@RequiredArgsConstructor
public class SkuSequenceRepository {

    private final JdbcTemplate jdbcTemplate;
    private static final String TABLE = "sku_sequences";

    public long nextValue(String sequenceKey) {
        // 1. Ensure table exists
        jdbcTemplate.execute(
                "CREATE TABLE IF NOT EXISTS " + TABLE + " (" +
                        "sequence_key VARCHAR(64) PRIMARY KEY," +
                        "next_value BIGINT NOT NULL" +
                        ")"
        );

        // 2. Initialize the key if it does not exist
        jdbcTemplate.update(
                "INSERT INTO " + TABLE + " (sequence_key, next_value) VALUES (?, ?) " +
                        "ON DUPLICATE KEY UPDATE next_value = next_value",
                sequenceKey, 1L
        );

        // 3. Atomically increment using update() instead of queryForObject()
        jdbcTemplate.update(
                "UPDATE " + TABLE + " SET " +
                        "next_value = LAST_INSERT_ID(next_value + 1) " +
                        "WHERE sequence_key = ?",
                sequenceKey
        );

        // 4. Retrieve the thread-safe LAST_INSERT_ID() generated by step 3
        return jdbcTemplate.queryForObject("SELECT LAST_INSERT_ID()", Long.class);
    }
}
