spring.application.name=ascenso


#===================
#DATABASE CONFIG
#++++++++++++++++++++
logging.level.org.springframework.boot.autoconfigure.jdbc=DEBUG
spring.datasource.url=jdbc:mysql://localhost:3306/ghwashaz?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=gh_user
spring.datasource.password=pass123
spring.jpa.properties.hibernate.default_schema=ghwashaz
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Hibernate config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#JWT config

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000


#SECURITY SETTINGS

spring.security.user.name=disabled
spring.security.user.password=disabled

#SERVER
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always


# ===============================
# LOGGING
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG

#JSON CONFIG

spring.jackson.serialization.indent_output=true
spring.jackson.default-property-inclusion=non_null


#HIKARI

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
